services:
  app:
    image: nginx:alpine
    container_name: labirinto-dev
    ports:
      - "3000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./style.css:/usr/share/nginx/html/style.css:ro
      - ./src:/usr/share/nginx/html/src:ro
      - ./apresentacao.html:/usr/share/nginx/html/apresentacao.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
